### ISSUE TITLE
Request for a Basic Usage Tutorial or Guide

### ISSUE THREAD

**Issue by takahirom** [mattprecious/stacker#199]
I think this is a great tool! Could we have a tutorial or guide for basic use cases? Something like this would be really helpful.

---

# Basic workflow

## Create a branch

st branch create some-branch

## Commit your changes

git commit -m "commit"

## Submit the branch

st branch submit

**Comment by mattprecious** [comment]
I'm glad you like it! If you've tried it out, I'm sure you've noticed that it's very incomplete and rough around the edges, both for installing and for using. While I've been using this for my day to day work for the past year, I don't consider it ready for wider adoption yet. It's still experimental and undergoing frequent infrastructure/API changes and I've just updated the README to indicate this.

With that in mind, I'm not in a place where I want to start writing guides and documentation. I will focus on that once things start to stabilize and are approaching an alpha release.
