### ISSUE TITLE
Generate libgit bindings as part of build

### ISSUE THREAD

**Issue by mattprecious** [mattprecious/stacker#26]
Currently they are checked in as a jar, but in order to properly support building libgit2 as part of the build (#24), the bindings also need to be generated as part of the build. From the README, the command I generated the current bindings with is:

```
jextract --output classes -t com.github \
  -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ \
  -I <libgit2folder>/include/ \
  -I <libgit2folder>/include/git2 \
  <libgit2folder>/include/git2.h
```

**Comment by JakeWharton** [comment]
#48
